### ISSUE TITLE
Support View Plus Device

### ISSUE THREAD

**Issue by ztroop** [ztroop/wave-reader-utils#10]
Add support for the new Airthings device, **View Plus**. Two things need to be done:

1. Add UUID and mapping data to supported devices.
2. Add particulate matter (PM2.5) sensor property.

**Comment by sdwilsh** [comment]
Is this issue still valid?  It seems like 0.0.7 may have covered the support.

**Comment by ztroop** [comment]
The `PM2.5` property was added to the `DeviceSensors` class, but `ViewPlus` was _not yet added as a supported device_. I need do some digging for the `ViewPlus`'s Characteristic UUID. If there's interest in this support, I can start working on it.

**Comment by sdwilsh** [comment]
I just acquired some of these devices, and am starting to look into how to get the data to report back to my MQTT server so I can integrate with Home Assistant.  I had assumed I was going to have to write something very much like this library, but I was happy to discover that it existed!

The UUID is `b42e2a68-ade7-11e4-89d3-123b93f75cba`, I think, based on the Airthings code: https://github.com/Airthings/waveplus-reader/blob/master/read_waveplus.py#L111

**Comment by ztroop** [comment]
Cool! I hope you find this useful! :) The `b42e2a68-ade7-11e4-89d3-123b93f75cba` Characteristic is specific the `WavePlus` only. Each model uses a different UUID or for the original `Wave` device, multiple UUIDs. There's some documentation available, but could be cleaned up and updated: https://ztroop.github.io/wave-reader-utils/specs/

**Comment by sdwilsh** [comment]
Got it.  I've not played with BLE before, so this is all a bit new to me, but I think I get what's going on with those docs.

**Comment by ztroop** [comment]
If you can, I'd recommend taking a look at `examples` for `get_services.py` to see available services for the `View Plus` and then poke around with `cli_usage.py` to read some of the characteristics and descriptors. With that complete, we can get a good picture around how it works.

**Comment by ztroop** [comment]
Tried to do a bit of RE on my own, but not too successful. I might have to bite the bullet and buy one of these suckers. 😆

**Comment by sdwilsh** [comment]
It turns out I can't find any of my bluetooth dongles, so getting data this weekend is not going to happen :(

I've got one on order, and I might find some time later in the week for this, or next weekend.

**Comment by sdwilsh** [comment]
I am such a clown.  For some reason I was thinking this issue was for the Wave Plus, but that looks to already have support.

**Comment by ztroop** [comment]
Oh! Yeah, that should definitely work without issues.

**Comment by ztroop** [comment]
As an update, there's no device information to work with and I don't own this device (or have plans to purchase it currently). I'm going to tag this as `help wanted`.

**Comment by ztroop** [comment]
@livnev That's excellent news! Always happy to have more contributors. 😄 Let me know if there's anything I can do to help once you start playing with the device.

**Comment by ztroop** [comment]
I'm sharing a discussion from https://github.com/ztroop/wave-reader-utils/pull/20, I think we might have hit a dead end this. I recently heard from a Airthings developer:

> You want to sync data (sensor values) over BLE from your View Plus? If so, this is unfortunately not possible. BLE is used for configuring the device, nothing else.

After the device is configured, it sends data over WiFi to the cloud. However, we could query the web API to retrieve this information. This library _does_ have a web component that provides this functionality, but it's dependent on the OpenAPI schema that Airthings publishes - which may, or may not be work.

At this point, I'm going to put this ticket to rest. Feel free to re-open if there are any further thoughts on this matter.
