### ISSUE TITLE
Historical data?

### ISSUE THREAD

**Issue by Sytten** [ztroop/wave-reader-utils#17]
Hi! Thanks for the hard work.
I am  currently using https://github.com/renemarc/balena-airthingswave to plug my wave into openHab.
Works great and all, but you don't seem to be able to fetch historical data from the device like the App can.
Since you did a bit of work with the device I was wondering if you knew how to sync the full dataset.

Thanks!

**Comment by ztroop** [comment]
Hi! I want to first apologize for the delayed response. You brought up an excellent point. A lot of existing scripts and community integrations with the Wave device family are only able to access current values. The Airthings mobile app is able to pull values over an extended period of time.

In short, I'm not exactly sure how it does that. I'd need to investigate that a bit more. Querying the device less often would also be an enhancement to battery life. There's definitely net benefit for supporting such a feature.

In the meantime, the web API does let you query historical data. That requires synchronizing the app with your device on a regular basis. Ideally, I'd like to remove the dependency on the mobile app moving forward.

**Comment by ztroop** [comment]
Better late than never, but windowing longer time periods from the device is possible using: `struct.pack("<BHHHH", 0x01, 2, 0, hours, 0)` where `hours` is the number of hours you want to go back. `1` week, for example would be `168` hours.

You can see this code in action in a project that uses `wave-reader-utils` as a dependency, see:
- https://github.com/ztroop/wave-plus-exporter/blob/main/exporter.py
