### ISSUE TITLE
Getting Device not found when searching for Wave2

### ISSUE THREAD

**Issue by KelvinSan** [ztroop/wave-reader-utils#18]
I have device connected to mobile app, it has been the only way the device shows up on Bluetooth network. When disconnected from mobile app device does not appear
EBUG:asyncio:Using proactor: IocpProactor
DEBUG:wave_reader.wave:Device: (F4:60:77:74:C6:2B) is a (WaveProduct.WAVE2) device.
INFO:wave_reader.wave:Device: (F4:60:77:74:C6:2B) connecting BLE client.
DEBUG:bleak.backends.winrt.scanner:Received 5C:60:BA:10:8A:F7: .
DEBUG:bleak.backends.winrt.scanner:skipping callback, waiting for scan response
DEBUG:bleak.backends.winrt.scanner:Received 5C:60:BA:10:8A:F7: .
DEBUG:bleak.backends.winrt.scanner:Received D1:39:32:37:0F:1E: Govee_H6051_0F1E.
DEBUG:bleak.backends.winrt.scanner:skipping callback, waiting for scan response
DEBUG:bleak.backends.winrt.scanner:Received C6:32:38:31:1F:37: Govee_H617A_1F37.
DEBUG:bleak.backends.winrt.scanner:skipping callback, waiting for scan response 
DEBUG:bleak.backends.winrt.scanner:Received C6:32:38:31:1F:37: Govee_H617A_1F37.
DEBUG:bleak.backends.winrt.scanner:Received 55:8B:8D:EB:7D:92: .
DEBUG:bleak.backends.winrt.scanner:skipping callback, waiting for scan response
DEBUG:bleak.backends.winrt.scanner:Received 55:8B:8D:EB:7D:92: .
DEBUG:bleak.backends.winrt.scanner:Received CC:32:38:31:6A:6C: Govee_H617A_6A6C.
DEBUG:bleak.backends.winrt.scanner:skipping callback, waiting for scan response 
DEBUG:bleak.backends.winrt.scanner:Received CC:32:38:31:6A:6C: Govee_H617A_6A6C.
DEBUG:bleak.backends.winrt.scanner:Received 7C:A6:B0:5F:67:38: GBK_H613D_6738.
DEBUG:bleak.backends.winrt.scanner:skipping callback, waiting for scan response
DEBUG:bleak.backends.winrt.scanner:Received 7C:A6:B0:5F:67:38: GBK_H613D_6738.
DEBUG:bleak.backends.winrt.scanner:Received C6:32:38:31:1F:37: Govee_H617A_1F37.
DEBUG:bleak.backends.winrt.scanner:Received C6:32:38:31:1F:37: Govee_H617A_1F37.
DEBUG:bleak.backends.winrt.scanner:Received 55:8B:8D:EB:7D:92: .
DEBUG:bleak.backends.winrt.scanner:Received CC:32:38:31:6A:6C: Govee_H617A_6A6C.
DEBUG:bleak.backends.winrt.scanner:Received CC:32:38:31:6A:6C: Govee_H617A_6A6C.
DEBUG:bleak.backends.winrt.scanner:Received 7C:A6:B0:5F:67:38: GBK_H613D_6738.
DEBUG:bleak.backends.winrt.scanner:Received 7C:A6:B0:5F:67:38: GBK_H613D_6738.
DEBUG:bleak.backends.winrt.scanner:Received C6:32:38:31:1F:37: Govee_H617A_1F37.
DEBUG:bleak.backends.winrt.scanner:Received C6:32:38:31:1F:37: Govee_H617A_1F37.
DEBUG:bleak.backends.winrt.scanner:Received D1:39:32:37:0F:1E: Govee_H6051_0F1E.
DEBUG:bleak.backends.winrt.scanner:Received 55:8B:8D:EB:7D:92: .
DEBUG:bleak.backends.winrt.scanner:Received 7C:A6:B0:5F:67:38: GBK_H613D_6738.
DEBUG:bleak.backends.winrt.scanner:Received C6:32:38:31:1F:37: Govee_H617A_1F37.
DEBUG:bleak.backends.winrt.scanner:Received C6:32:38:31:1F:37: Govee_H617A_1F37.
DEBUG:bleak.backends.winrt.scanner:Received D1:39:32:37:0F:1E: Govee_H6051_0F1E.
DEBUG:bleak.backends.winrt.scanner:Received CC:32:38:31:6A:6C: Govee_H617A_6A6C.
DEBUG:bleak.backends.winrt.scanner:Received CC:32:38:31:6A:6C: Govee_H617A_6A6C.
DEBUG:bleak.backends.winrt.scanner:Received CC:32:38:31:6A:6C: Govee_H617A_6A6C.
DEBUG:bleak.backends.winrt.scanner:Received 7C:A6:B0:5F:67:38: GBK_H613D_6738.
DEBUG:bleak.backends.winrt.scanner:Received 55:8B:8D:EB:7D:92: .
DEBUG:bleak.backends.winrt.scanner:Received 55:8B:8D:EB:7D:92: .
DEBUG:bleak.backends.winrt.scanner:Received 7C:A6:B0:5F:67:38: GBK_H613D_6738.
DEBUG:bleak.backends.winrt.scanner:Received 7C:A6:B0:5F:67:38: GBK_H613D_6738.
DEBUG:bleak.backends.winrt.scanner:Received C6:32:38:31:1F:37: Govee_H617A_1F37.
DEBUG:bleak.backends.winrt.scanner:Received C6:32:38:31:1F:37: Govee_H617A_1F37.
DEBUG:bleak.backends.winrt.scanner:Received D1:39:32:37:0F:1E: Govee_H6051_0F1E.
DEBUG:bleak.backends.winrt.scanner:Received 62:97:C5:3D:6D:68: .
DEBUG:bleak.backends.winrt.scanner:Received CC:32:38:31:6A:6C: Govee_H617A_6A6C.
DEBUG:bleak.backends.winrt.scanner:Received D1:39:32:37:0F:1E: Govee_H6051_0F1E.
DEBUG:bleak.backends.winrt.scanner:Received D1:39:32:37:0F:1E: Govee_H6051_0F1E.
DEBUG:bleak.backends.winrt.scanner:Received C6:32:38:31:1F:37: Govee_H617A_1F37.
DEBUG:bleak.backends.winrt.scanner:Received C6:32:38:31:1F:37: Govee_H617A_1F37.
DEBUG:bleak.backends.winrt.scanner:Received F4:60:77:74:C6:2B: .
DEBUG:bleak.backends.winrt.scanner:skipping callback, waiting for scan response
DEBUG:bleak.backends.winrt.scanner:Received 7C:A6:B0:5F:67:38: GBK_H613D_6738.
DEBUG:bleak.backends.winrt.scanner:Received 7C:A6:B0:5F:67:38: GBK_H613D_6738.
DEBUG:bleak.backends.winrt.scanner:Received 5C:60:BA:10:8A:F7: .
DEBUG:bleak.backends.winrt.scanner:Received C6:32:38:31:1F:37: Govee_H617A_1F37.
DEBUG:bleak.backends.winrt.scanner:Received C6:32:38:31:1F:37: Govee_H617A_1F37.
DEBUG:bleak.backends.winrt.scanner:Received 7C:A6:B0:5F:67:38: GBK_H613D_6738.
DEBUG:bleak.backends.winrt.scanner:Received 62:97:C5:3D:6D:68: .
DEBUG:bleak.backends.winrt.scanner:Received CC:32:38:31:6A:6C: Govee_H617A_6A6C.
DEBUG:bleak.backends.winrt.scanner:Received EC:81:93:2D:54:F5: .
DEBUG:bleak.backends.winrt.scanner:skipping callback, waiting for scan response
DEBUG:bleak.backends.winrt.scanner:Received 7C:A6:B0:5F:67:38: GBK_H613D_6738.
DEBUG:bleak.backends.winrt.scanner:Received CC:32:38:31:6A:6C: Govee_H617A_6A6C.
DEBUG:bleak.backends.winrt.scanner:Received CC:32:38:31:6A:6C: Govee_H617A_6A6C.
DEBUG:bleak.backends.winrt.scanner:Received 7C:A6:B0:5F:67:38: GBK_H613D_6738.
DEBUG:bleak.backends.winrt.scanner:Received D1:39:32:37:0F:1E: Govee_H6051_0F1E.
DEBUG:bleak.backends.winrt.scanner:Received D1:39:32:37:0F:1E: Govee_H6051_0F1E.
DEBUG:bleak.backends.winrt.scanner:Received C6:32:38:31:1F:37: Govee_H617A_1F37.
DEBUG:bleak.backends.winrt.scanner:Received 5C:60:BA:10:8A:F7: .
DEBUG:bleak.backends.winrt.scanner:Received 5C:60:BA:10:8A:F7: .
DEBUG:bleak.backends.winrt.scanner:Received 5C:60:BA:10:8A:F7: .
DEBUG:bleak.backends.winrt.scanner:Received 5C:60:BA:10:8A:F7: .
DEBUG:bleak.backends.winrt.scanner:Received CC:32:38:31:6A:6C: Govee_H617A_6A6C.
DEBUG:bleak.backends.winrt.scanner:Received CC:32:38:31:6A:6C: Govee_H617A_6A6C.
DEBUG:bleak.backends.winrt.scanner:Received 62:97:C5:3D:6D:68: .
DEBUG:bleak.backends.winrt.scanner:Received C6:32:38:31:1F:37: Govee_H617A_1F37.
DEBUG:bleak.backends.winrt.scanner:7 devices found. Watcher status: 3.
Traceback (most recent call last):
  File "C:\Users\ronro\OneDrive\Desktop\Github\PIPHI-CLI-v2\app\lib\airthings.py", line 24, in <module>
    loop.run_until_complete(run(args))
  File "C:\Python39\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "C:\Users\ronro\OneDrive\Desktop\Github\PIPHI-CLI-v2\app\lib\airthings.py", line 13, in run
    async with WaveDevice.create(args.address, args.serial) as conn:
  File "C:\Users\ronro\OneDrive\Desktop\Github\PIPHI-CLI-v2\venv\lib\site-packages\wave_reader\wave.py", line 136, in __aenter__
    await self.connect()
  File "C:\Users\ronro\OneDrive\Desktop\Github\PIPHI-CLI-v2\venv\lib\site-packages\wave_reader\wave.py", line 164, in connect
    return await self._client.connect()
  File "C:\Users\ronro\OneDrive\Desktop\Github\PIPHI-CLI-v2\venv\lib\site-packages\bleak\__init__.py", line 471, in connect
    return await self._backend.connect(**kwargs)
  File "C:\Users\ronro\OneDrive\Desktop\Github\PIPHI-CLI-v2\venv\lib\site-packages\bleak\backends\winrt\client.py", line 244, in connect
    raise BleakDeviceNotFoundError(
bleak.exc.BleakDeviceNotFoundError: Device with address F4:60:77:74:C6:2B was not found.

**Comment by ztroop** [comment]
Thanks for the feedback! I'll take a look into this.

**Comment by ztroop** [comment]
I spent a little time looking at the bluetooth client library, `bleak` and [I see that we can modify the default timeout](https://github.com/hbldh/bleak/blob/96ced27f82e9b166834a8f91e1d1103fe09719d6/bleak/__init__.py#L199) for scanning. I'll make a change in the library to make the timeout configurable.

It also looks like you're running on Windows, I'd be curious to see what the more verbose output (directly from `bleak`), [try this](https://bleak.readthedocs.io/en/latest/troubleshooting.html#enable-logging)! That might reveal more information as well if it's an issue beyond the timeout being too short for scanning.

**Comment by KelvinSan** [comment]
Ok so will this fix the inconsistency of the device not showing up ? And yes I am running on windows @ztroop

**Comment by ztroop** [comment]
Without more information, I can only assume by examining at the logs, it looks like scanning finishes before it can find the device. Increasing the scanning timeout _may resolve your issue_. You could try getting more logs from the suggestion I made above if you're still running into problems. 

I should have the `1.0.0` release out before end of day.

**Comment by ztroop** [comment]
You should be able to use version `1.0.0` now. You can use the `timeout` keyword argument. I'd recommend `10.0` or `15.0` and see if the scanning will pick up the device. A [code example is available](https://github.com/ztroop/wave-reader-utils/blob/master/examples/basic_usage.py).

**Comment by ztroop** [comment]
I think this is solved. If you are still experiencing the problem with the newest version, re-open the ticket.
