### ISSUE TITLE
Documentation of Wave devices

### ISSUE THREAD

**Issue by jschornick** [ztroop/wave-reader-utils#3]
While the code in this project (as well as that in the official repos) is a great resource, it would be helpful to have a dedicated place to describe and document the behavior of all the Airthings Wave devices. 

For example:

- description of each supported device (name, model, sensors)
- available BLE attributes (vendor-specific and generic)
- data formats / how to decode responses
- update rates / communication best practices

A simple page in this project's wiki might be a good start, with some attention to keeping the information language-agnostic and useful to other projects. 

I've collected some notes while poking at my gen2 Wave which may be a reasonable jumping off point in a [gist](https://gist.github.com/jschornick/8c31ce1268c261bb3dd45130ea3a672e).

Thoughts?

**Comment by ztroop** [comment]
I really like the idea. A wiki is an option, but a `docs` folder that publishes to `GitHub Pages` might be more collaborative. Thoughts on that?

**Comment by jschornick** [comment]
No strong opinions here. Any (accurate!) documentation would be an improvement, so I'd avoid bikeshedding the issue too much. Migration would be easy enough if/when a better option presents itself.

So if you have a documentation/publication system that you like and is amenable to an average contributor, I'm all ears. What do you propose?

**Comment by ztroop** [comment]
There's now a `docs` folder. The markdown files are built using `mkdocs` and changes are automatically published to the [project documentation site](https://ztroop.github.io/wave-reader-utils/). It's as simple as adding to the markdown files now. :smile:

**Comment by ztroop** [comment]
@jschornick #7 was merged. Any objection to closing this?

**Comment by jschornick** [comment]
Looks great, thanks!
