### ISSUE TITLE
Occasional connection abort from BlueZ

### ISSUE THREAD

**Issue by jschornick** [ztroop/wave-reader-utils#5]
Somewhat rarely, but yet on more than one occasion, I've experienced a connection abort when retrieving sensor values from my 2nd gen Wave.

Here's the error when running the included `examples/cli.py` (only modified to include my device address and model):

```
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/bleak/backends/bluezdbus/client.py", line 133, in connect
    await self._bus.callRemote(
txdbus.error.RemoteError: org.bluez.Error.Failed: Software caused connection abort

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jeff/airthings/wru/cli.py", line 25, in <module>
    loop.run_until_complete(device.get_sensor_values())
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/home/jeff/airthings/wru/wave_reader/wave.py", line 144, in get_sensor_values
    async with BleakClient(self.address) as client:
  File "/usr/lib/python3.9/site-packages/bleak/backends/client.py", line 59, in __aenter__
    await self.connect()
  File "/usr/lib/python3.9/site-packages/bleak/backends/bluezdbus/client.py", line 150, in connect
    raise BleakError(str(e))
bleak.exc.BleakError: org.bluez.Error.Failed: Software caused connection abort
```

Currently running the example program in a loop, I'm seeing this failure approximately once for every 10-20 attempts. After failing, the next run works as expected without any intervention/changes on my part.

I'll try to dig into this more tomorrow, but wanted to see if this is a known issue. I don't have enough BLE experience to know if this type of connection failure should be expected and handled/retried by the client.

**Comment by ztroop** [comment]
Indeed! I've seen this in [bleak](https://github.com/hbldh/bleak) issues. It's not exactly clear, but suggested [here](https://github.com/hbldh/bleak/issues/172):
> It might be alleviated if #236 is worked on. It might be due to txdbus and how it handles the DBus connections.

**Comment by ztroop** [comment]
I added a `retry` decorator to help mitigate against transient `BleakError` issues. #6 for details. That doesn't solve the problem, but at least makes things a bit more user friendly.

**Comment by jschornick** [comment]
Sadly, this doesn't seem to improve the rate of errors which bubble up to the application. If you can't reproduce it on your end, I'll try to figure out why the decorator/wrapper around `get_sensor_values` isn't doing the trick.

**Comment by ztroop** [comment]
Hmm. I haven't run into this issue, so it's difficult to determine what's happening. Ideally, we should insulate `BleakError` exceptions from the users because `bleak` should be in the background as an implementation detail.

**Comment by ztroop** [comment]
I've finally been able to reproduce this and working on a solution. It looks like we're not able to catch the raised exceptions with the `retry()` decorator in the asynchronous backend.

We might be able to implement an exception handler via `loop.set_exception_handler(handle_exception)`, but I'm still investigating,

**Comment by ztroop** [comment]
I think the best solution at this time is to update the documentation and examples to demonstrate exception handling in `asyncio`.
- https://docs.python.org/3/library/asyncio-eventloop.html#error-handling-api

Final thoughts, @jschornick ?

**Comment by sdwilsh** [comment]
There is [`retrying-async`](https://pypi.org/project/retrying-async/), which might be a viable option.

Although, I'd say my preferred solution would be to return a [`Future`](https://docs.python.org/3/library/asyncio-future.html#future-object) and either set the result or set the exception when wrapping the `connect` call in a try-except.  That lets calling code control how often they retry, and how to handle if it is not working properly.

**Comment by ztroop** [comment]
I appreciate the input @sdwilsh! I like the idea. I'll look into it as soon as I can. Open to PRs as well.

**Comment by sdwilsh** [comment]
If you don't get to it in the next week or two, I might look into doing a PR as well :)

Right now I'm in the explore and plan phase of my project, and I don't have a lot of time available to work on it anyway.

**Comment by ztroop** [comment]
I was thinking about this for a little bit. I removed the `retry` decorator from the code base and added a convenience function `run()` for `asyncio` operation and error handling. We're using `asyncio.gather(.., return_exceptions=True)`, that allows proper `try` logic and that seems to work.

I see this as particularly useful to novice programmers that want to control their Airthings data. Take a look at the `0.0.8` branch. Is this what you had in mind? @sdwilsh

**Comment by sdwilsh** [comment]
It's not a bad approach.  I might still come along with a PR for a more advanced asyncio API when I have some time to work on my project, but this solves the immediate issue.

**Comment by ztroop** [comment]
Immediate issue is resolved. Always open to more advanced `asyncio` API. Looking forward to it! Cheers.
